#!/bin/bash
#This script tells a story based on /etc/passwd

while IFS=: read -r username password uid gid comment home shell
do
echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info abou the user here: $username"
done < /etc/passwd

