#!/usr/bin/env bash
# Displays the PID and processs name of processes the word bash

for pid in /proc/[0-9]*; do
if [ -f "$pid/comm" ] && grep -q bash "$pid/comm"; then
echo "$(basename "$pid") bash"
fi
done
